spring:
  application:
    name: scraper

logging:
  level:
    org.springframework.security: INFO

browser:
  backoff: 5000
  retryCount: 3

scraper:
  google:
    enabled: true
    delay: 480000
    errorDelay: 480000
    linkSelector: "#rso > div > div > div > div > div > h3 > a"
    first: 0
    resultCount: 100
    pageSize: 100
    useProxy: true

  bing:
    enabled: true
    delay: 480000
    errorDelay: 480000
    linkSelector: "#b_results > li > h2 > a"
    first: 1
    resultCount: 100
    pageSize: 10
    useProxy: true

  yahoo:
    enabled: true
    delay: 480000
    errorDelay: 480000
    linkSelector: "#web > ol > li > div > div > h3 > a"
    first: 1
    resultCount: 100
    pageSize: 100
    useProxy: true

  yandex:
    enabled: false
    delay: 480000
    errorDelay: 480000
    linkSelector:
    first: 0
    resultCount: 100
    pageSize: 100
    useProxy: true

  duckduckgo:
    enabled: false
    delay: 480000
    errorDelay: 480000
    linkSelector:
    first: 0
    resultCount: 100
    pageSize: 100
    useProxy: true